### ISSUE TITLE
[Refactor] 레이아웃 리팩토링

### ISSUE THREAD

**Issue by 6uohul** [team-peekabook/Peekabook-iOS#63]
## 🛠 Issue

레이아웃 리팩토링

## 📝 To-do

- [x] 사용자 검색 시 탭바 숨기기 코드 수정
- [x] 추천 탭 뷰 라벨 레이아웃 경고 수정

**Comment by ziwoohan** [comment]
상당히 P다운 계획이네요. 멋져요 ! 🍪
